netbox:
  base_url: "https://netbox.example.com"
  timeout: 30

librenms:
  base_url: "https://librenms.example.com"
  timeout: 30

logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: 'network_agent.log'